[features]
seeds = false
skip-lint = false

[programs.devnet]
daemon_registry = "3nu6sppjDtAKNoBbUAhvFJ35B2JsxpRY6G4Cg72MCJRc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
