/**
 * Raw source for the Phaser Solana game template ("Starfall"), embedded as
 * plain strings so ProjectStarter can write them verbatim during scaffolding.
 *
 * These are stored as line arrays joined with '\n' rather than template
 * literals because the game source itself contains backticks and ${} — keeping
 * them as data avoids any template-literal escaping ambiguity. The four hub
 * seams (types/index/stub/manifest) match daemon-game-studio's arcade-starter.
 */

export const GAME_MAIN_TS = [
  "import Phaser from 'phaser'",
  "import { GameScene } from './game/GameScene'",
  "import { manifest } from './daemon'",
  '',
  "// Entry point. The hub's GamePlayer mounts this build in an embedded surface;",
  '// standalone it runs from `npm run dev`.',
  '',
  'document.title = manifest.title',
  '',
  'new Phaser.Game({',
  '  type: Phaser.AUTO,',
  "  parent: 'app',",
  '  width: 480,',
  '  height: 720,',
  "  backgroundColor: '#0a0a12',",
  '  physics: {',
  "    default: 'arcade',",
  '    arcade: { gravity: { x: 0, y: 0 }, debug: false },',
  '  },',
  '  scale: {',
  '    mode: Phaser.Scale.FIT,',
  '    autoCenter: Phaser.Scale.CENTER_BOTH,',
  '  },',
  '  scene: [GameScene],',
  '})',
  '',
].join('\n')

export const GAME_SCENE_TS = [
  "import Phaser from 'phaser'",
  "import { getBridge } from '../daemon'",
  '',
  '// Starfall: a 60-second score-attack. Move the ship left/right, catch stars for',
  '// points, dodge falling rocks. When time runs out, the run\'s score is recorded',
  '// on-chain (via the DAEMON bridge) and a trophy cNFT is minted for a new best.',
  '//',
  '// This is a REAL loop, not a skeleton: input, spawning, collision, scoring,',
  '// difficulty ramp, game-over, and the on-chain hook are all implemented.',
  '',
  'const GAME_MS = 60_000',
  'const SHIP_SPEED = 420',
  'const STAR_POINTS = 10',
  '',
  'export class GameScene extends Phaser.Scene {',
  '  private ship!: Phaser.GameObjects.Rectangle',
  '  private stars!: Phaser.Physics.Arcade.Group',
  '  private rocks!: Phaser.Physics.Arcade.Group',
  '  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys',
  '  private scoreText!: Phaser.GameObjects.Text',
  '  private timeText!: Phaser.GameObjects.Text',
  '  private statusText!: Phaser.GameObjects.Text',
  '  private score = 0',
  '  private endsAt = 0',
  '  private spawnEvent?: Phaser.Time.TimerEvent',
  '  private running = false',
  "  private best = Number(localStorage.getItem('starfall_best') ?? '0')",
  '',
  '  constructor() {',
  "    super('game')",
  '  }',
  '',
  '  create() {',
  '    const { width, height } = this.scale',
  '',
  '    this.add.rectangle(width / 2, height / 2, width, height, 0x0a0a12)',
  '    this.ship = this.add.rectangle(width / 2, height - 40, 44, 20, 0x4cd4c4)',
  '    this.physics.add.existing(this.ship)',
  '    ;(this.ship.body as Phaser.Physics.Arcade.Body).setCollideWorldBounds(true)',
  '',
  '    this.stars = this.physics.add.group()',
  '    this.rocks = this.physics.add.group()',
  '',
  "    this.scoreText = this.add.text(16, 14, 'SCORE 0', fontStyle())",
  "    this.timeText = this.add.text(width - 16, 14, '60', fontStyle()).setOrigin(1, 0)",
  '    this.statusText = this.add',
  "      .text(width / 2, height / 2, '', fontStyle(20))",
  '      .setOrigin(0.5)',
  '',
  '    this.cursors = this.input.keyboard!.createCursorKeys()',
  "    this.input.keyboard!.on('keydown-SPACE', () => {",
  '      if (!this.running) this.startRun()',
  '    })',
  "    this.input.on('pointerdown', () => {",
  '      if (!this.running) this.startRun()',
  '    })',
  '',
  '    this.physics.add.overlap(this.ship, this.stars, (_s, star) => {',
  '      ;(star as Phaser.GameObjects.Rectangle).destroy()',
  '      this.score += STAR_POINTS',
  '      this.scoreText.setText(`SCORE ${this.score}`)',
  '    })',
  "    this.physics.add.overlap(this.ship, this.rocks, () => this.endRun('HIT'))",
  '',
  '    this.showIdle()',
  '  }',
  '',
  '  private showIdle() {',
  '    this.statusText.setText(`STARFALL\\nbest ${this.best}\\n\\nSPACE / tap to start`).setAlpha(1)',
  '  }',
  '',
  '  private startRun() {',
  '    this.score = 0',
  "    this.scoreText.setText('SCORE 0')",
  '    this.stars.clear(true, true)',
  '    this.rocks.clear(true, true)',
  '    this.statusText.setAlpha(0)',
  '    this.running = true',
  '    this.endsAt = this.time.now + GAME_MS',
  '    this.spawnEvent = this.time.addEvent({',
  '      delay: 650,',
  '      loop: true,',
  '      callback: () => this.spawn(),',
  '    })',
  '  }',
  '',
  '  private spawn() {',
  '    const x = Phaser.Math.Between(20, this.scale.width - 20)',
  '    const elapsed = 1 - Math.max(0, this.endsAt - this.time.now) / GAME_MS',
  '    const rockChance = 0.35 + elapsed * 0.3 // difficulty ramps up',
  '    const isRock = Math.random() < rockChance',
  '    const group = isRock ? this.rocks : this.stars',
  '    const color = isRock ? 0xff5a6a : 0xffd447',
  '    const obj = this.add.rectangle(x, -20, isRock ? 22 : 16, isRock ? 22 : 16, color)',
  '    this.physics.add.existing(obj)',
  '    const body = obj.body as Phaser.Physics.Arcade.Body',
  '    body.setVelocityY(160 + elapsed * 180)',
  '    group.add(obj)',
  '  }',
  '',
  "  private endRun(reason: 'TIME' | 'HIT') {",
  '    if (!this.running) return',
  '    this.running = false',
  '    this.spawnEvent?.remove()',
  '    this.stars.setVelocityY(0)',
  '    this.rocks.setVelocityY(0)',
  '',
  '    const isBest = this.score > this.best',
  '    if (isBest) {',
  '      this.best = this.score',
  "      localStorage.setItem('starfall_best', String(this.best))",
  '    }',
  "    this.statusText.setText(`${reason === 'HIT' ? 'CRASHED' : 'TIME'}\\nscore ${this.score}`).setAlpha(1)",
  '    void this.settle(isBest)',
  '  }',
  '',
  '  /** Record the run on-chain and mint a trophy on a new best (via DAEMON). */',
  '  private async settle(isBest: boolean) {',
  '    const bridge = getBridge()',
  '    try {',
  '      if (!bridge.getSession()) await bridge.connect()',
  '      const outcome = await bridge.recordOutcome({ score: this.score })',
  "      let line = outcome.ok ? 'run recorded' : `not recorded: ${outcome.error}`",
  '      if (isBest && outcome.ok) {',
  "        const asset = await bridge.mintAsset({ name: `Starfall ${this.score}`, kind: 'trophy' })",
  "        line += `\\ntrophy minted (${asset.onChain ? 'on-chain' : 'local'})`",
  '      }',
  '      this.statusText.setText(`${this.statusText.text}\\n${line}\\n\\nSPACE / tap to retry`)',
  '    } catch (err) {',
  '      this.statusText.setText(`${this.statusText.text}\\n(settle error)\\n\\nSPACE / tap to retry`)',
  '      console.error(err)',
  '    }',
  '  }',
  '',
  '  update() {',
  '    if (this.running) {',
  '      const body = this.ship.body as Phaser.Physics.Arcade.Body',
  '      const left = this.cursors.left.isDown || this.pointerLeft()',
  '      const right = this.cursors.right.isDown || this.pointerRight()',
  '      body.setVelocityX(left ? -SHIP_SPEED : right ? SHIP_SPEED : 0)',
  '',
  '      const remaining = Math.max(0, this.endsAt - this.time.now)',
  '      this.timeText.setText(String(Math.ceil(remaining / 1000)))',
  "      if (remaining <= 0) this.endRun('TIME')",
  '',
  '      this.cull(this.stars)',
  '      this.cull(this.rocks)',
  '    }',
  '  }',
  '',
  '  private pointerLeft() {',
  '    return this.input.activePointer.isDown && this.input.activePointer.x < this.scale.width / 2',
  '  }',
  '  private pointerRight() {',
  '    return this.input.activePointer.isDown && this.input.activePointer.x >= this.scale.width / 2',
  '  }',
  '',
  '  private cull(group: Phaser.Physics.Arcade.Group) {',
  '    group.children.each((child) => {',
  '      const go = child as Phaser.GameObjects.Rectangle',
  '      if (go.y > this.scale.height + 30) go.destroy()',
  '      return true',
  '    })',
  '  }',
  '}',
  '',
  'function fontStyle(size = 16): Phaser.Types.GameObjects.Text.TextStyle {',
  '  return {',
  "    fontFamily: 'monospace',",
  '    fontSize: `${size}px`,',
  "    color: '#e8e8f0',",
  "    align: 'center',",
  '  }',
  '}',
  '',
].join('\n')

export const GAME_DAEMON_TYPES_TS = [
  '// DAEMON Game Hub — integration contract.',
  '//',
  '// These are the four seams every hub game plugs into. The starter ships with',
  '// working *stub* implementations (see ./stub.ts) so the game is playable the',
  '// moment you clone it. When a game is published through the hub, the DAEMON',
  '// swarm replaces the stubs with real implementations backed by:',
  '//   - wallet/onboarding -> GameShift or Privy/Turnkey (seedless, gasless)',
  '//   - assets            -> Metaplex (cNFT via Bubblegum / Core)',
  '//   - signing           -> DAEMON SignerGuardService (per-game policy caps)',
  '//   - publish manifest   -> game_registry provenance record',
  '//',
  '// The game code depends ONLY on these interfaces, never on a concrete SDK.',
  '// That is the studio-in-a-box promise: swap the impl, the game is unchanged.',
  '',
  '/** A player\'s session identity. Seedless: no seed phrase ever shown. */',
  'export interface PlayerSession {',
  '  /** base58 public key of the session/embedded wallet */',
  '  address: string',
  '  /** display handle if the onboarding provider gives one */',
  '  label?: string',
  '  /** true when a real (non-stub) wallet is connected */',
  '  live: boolean',
  '}',
  '',
  "/** Result of routing an on-chain action through DAEMON's signing guard. */",
  'export interface SignResult {',
  '  ok: boolean',
  '  /** tx signature when ok; error reason when not */',
  '  signature?: string',
  '  error?: string',
  '  /** true if the action was blocked by the per-game signing policy */',
  '  blockedByPolicy?: boolean',
  '}',
  '',
  '/** A minted in-game asset (e.g. a high-score trophy cNFT). */',
  'export interface MintedAsset {',
  '  assetId: string',
  '  name: string',
  '  /** true if minted on-chain, false if this is a stub/local mint */',
  '  onChain: boolean',
  '}',
  '',
  '/**',
  ' * The per-game signing policy the hub attaches at publish time. The game',
  ' * declares the programs it needs; DAEMON\'s SignerGuardService enforces that',
  ' * the game can invoke NOTHING else and cannot exceed the value cap. This is',
  ' * why a hub game is safe-by-construction: it literally cannot drain a player.',
  ' */',
  'export interface GameSigningPolicy {',
  '  /** program IDs this game is allowed to invoke */',
  '  allowedPrograms: string[]',
  '  /** max lamports the game may move per action (0 = no value transfer) */',
  '  maxLamportsPerAction: number',
  '  /** require an explicit player approval card above this lamports amount */',
  '  approvalThresholdLamports: number',
  '}',
  '',
  '/** The DAEMON bridge the game talks to. Injected by the hub\'s GamePlayer. */',
  'export interface DaemonBridge {',
  '  /** Connect a seedless session wallet (no seed phrase). */',
  '  connect(): Promise<PlayerSession>',
  '  /** Current session, or null if not connected. */',
  '  getSession(): PlayerSession | null',
  '  /** Mint an in-game asset. Routed through the signing guard. */',
  "  mintAsset(input: { name: string; kind: 'trophy' | 'cosmetic' }): Promise<MintedAsset>",
  '  /** Record a game outcome on-chain (score/win). Routed through the guard. */',
  '  recordOutcome(input: { score: number; meta?: Record<string, unknown> }): Promise<SignResult>',
  '  /** The signing policy in force for this game (for display/debug). */',
  '  policy(): GameSigningPolicy',
  '}',
  '',
].join('\n')

export const GAME_DAEMON_INDEX_TS = [
  "// Bridge resolver. The hub's GamePlayer injects a real DaemonBridge on",
  '// window.__DAEMON__ at runtime. When absent (standalone dev), we fall back to',
  '// the stub so the game always runs.',
  '',
  "import type { DaemonBridge } from './types'",
  "import { stubBridge } from './stub'",
  '',
  'declare global {',
  '  interface Window {',
  '    __DAEMON__?: DaemonBridge',
  '  }',
  '}',
  '',
  'export function getBridge(): DaemonBridge {',
  "  if (typeof window !== 'undefined' && window.__DAEMON__) {",
  '    return window.__DAEMON__',
  '  }',
  '  return stubBridge',
  '}',
  '',
  "export * from './types'",
  "export { manifest } from './manifest'",
  '',
].join('\n')

export const GAME_DAEMON_STUB_TS = [
  '// Stub DaemonBridge — makes the template playable standalone (no SDKs, no chain).',
  '//',
  '// Every method mimics the real behavior locally so a dev can run the game and',
  '// see the full loop (connect -> play -> mint trophy -> record outcome) before',
  '// any real integration. The swarm replaces this file with a real bridge at',
  '// publish time; the game code never changes.',
  '//',
  '// The signing policy below is REAL in spirit: it demonstrates the safe-by-',
  '// construction guarantee. mintAsset/recordOutcome check the policy locally the',
  '// same way SignerGuardService.assertTransactionAllowed() will on-chain.',
  '',
  'import type {',
  '  DaemonBridge,',
  '  GameSigningPolicy,',
  '  MintedAsset,',
  '  PlayerSession,',
  '  SignResult,',
  "} from './types'",
  '',
  '// Memo program — the only thing this game needs to write a score/outcome memo.',
  '// A real build would swap in the actual program(s); the point is the game is',
  '// capped to THIS list and cannot invoke anything else.',
  "const MEMO_PROGRAM = 'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr'",
  '',
  'const POLICY: GameSigningPolicy = {',
  '  allowedPrograms: [MEMO_PROGRAM],',
  '  maxLamportsPerAction: 0, // this game never moves value — pure score/asset writes',
  '  approvalThresholdLamports: 0,',
  '}',
  '',
  'function fakeAddress(): string {',
  '  // deterministic-ish base58-looking string; no crypto, this is a stub',
  "  const chars = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'",
  "  let s = ''",
  '  for (let i = 0; i < 44; i++) s += chars[(i * 7 + 13) % chars.length]',
  '  return s',
  '}',
  '',
  'let session: PlayerSession | null = null',
  'let assetCounter = 0',
  '',
  '/** Local policy check mirroring SignerGuardService.assertTransactionAllowed. */',
  'function policyAllows(programId: string, lamports: number): { ok: boolean; reason?: string } {',
  '  if (!POLICY.allowedPrograms.includes(programId)) {',
  '    return { ok: false, reason: `program ${programId} not in game policy` }',
  '  }',
  '  if (lamports > POLICY.maxLamportsPerAction) {',
  '    return { ok: false, reason: `value ${lamports} exceeds cap ${POLICY.maxLamportsPerAction}` }',
  '  }',
  '  return { ok: true }',
  '}',
  '',
  'export const stubBridge: DaemonBridge = {',
  '  async connect(): Promise<PlayerSession> {',
  "    session = { address: fakeAddress(), label: 'guest', live: false }",
  '    return session',
  '  },',
  '',
  '  getSession(): PlayerSession | null {',
  '    return session',
  '  },',
  '',
  '  async mintAsset({ name, kind }): Promise<MintedAsset> {',
  '    const check = policyAllows(MEMO_PROGRAM, 0)',
  '    if (!check.ok) throw new Error(`mint blocked: ${check.reason}`)',
  '    assetCounter += 1',
  '    return { assetId: `stub-${kind}-${assetCounter}`, name, onChain: false }',
  '  },',
  '',
  '  async recordOutcome({ score }): Promise<SignResult> {',
  '    const check = policyAllows(MEMO_PROGRAM, 0)',
  '    if (!check.ok) return { ok: false, error: check.reason, blockedByPolicy: true }',
  '    // stub "signature"',
  '    return { ok: true, signature: `stub-sig-${score}-${Date.now().toString(36)}` }',
  '  },',
  '',
  '  policy(): GameSigningPolicy {',
  '    return POLICY',
  '  },',
  '}',
  '',
].join('\n')
